spring:
  application:
    name: pass-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: ${SPRING_PROFILES_INCLUDE:swagger,datasource,actuator,grpc,redis}

firebase:
  project-id: keywe-ed485
  key-path: firebase-service-account.json